apiVersion: v1
kind: Service
metadata:
  name: demoapp-service
  namespace: demoapp-ns

spec:
  type: NodePort
  selector:
    app: demoapp

  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30082


